# This file was generated by GoReleaser. DO NOT EDIT.
cask "gomanager" do
  name "gomanager"
  desc ""
  homepage ""
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gomanager"
  bash_completion "completions/gomanager.bash"
  zsh_completion "completions/gomanager.zsh"
  fish_completion "completions/gomanager.fish"

  on_macos do
    on_intel do
      url "https://github.com/tcondeixa/gomanager/releases/download/v#{version}/gomanager-#{version}-darwin-amd64.tar.gz"
      sha256 "ccc30ac0c7a69f4184c724ac600cafb2cb1b832f45a54e744a11390e3b8867f2"
    end
    on_arm do
      url "https://github.com/tcondeixa/gomanager/releases/download/v#{version}/gomanager-#{version}-darwin-arm64.tar.gz"
      sha256 "1db2be6b388860369d0ceb2882da0255f872f8aa966502a24feece665adc77d6"
    end
  end

  # No zap stanza required
end
