# This file was generated by GoReleaser. DO NOT EDIT.
cask "gomanager" do
  name "gomanager"
  desc "cli to manage go binaries"
  homepage "https://github.com/tcondeixa/gomanager"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gomanager"
  bash_completion "completions/gomana.h"
  zsh_completion "completions/gomanager.zsh"
  fish_completion "completions/gomanager.fish"

  on_macos do
    on_intel do
      url "https://github.com/tcondeixa/gomanager/releases/download/v#{version}/gomanager-#{version}-darwin-amd64.tar.gz"
      sha256 "a8a470283eda56d807b117011d63ecd2fca564b773e432905f70e6894bcfe7e1"
    end
    on_arm do
      url "https://github.com/tcondeixa/gomanager/releases/download/v#{version}/gomanager-#{version}-darwin-arm64.tar.gz"
      sha256 "ee27ad987dcaef8a3b71f621625c231696f7441a804fea521c5ee0bf343646f5"
    end
  end

  # No zap stanza required
end
